name: deploy

on:
  push:
    branches:
        - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Confirm merge
        run: echo "Test Request is merged x 5"